---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      labels:
        app: scheduler
        istio: monitor
    spec:
      containers:
        - image: esdg9t1/scheduler:latest
          imagePullPolicy: Always
          name: scheduler
          env:
            - name: SERVICE
              value: scheduler
          ports:
            - name: http
              containerPort: 8080
