---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
        istio: monitor
    spec:
      containers:
        - image: esdg9t1/users:latest
          imagePullPolicy: Always
          name: users
          env:
            - name: SERVICE
              value: users
          ports:
            - name: http
              containerPort: 8080
