---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notify
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notify
  template:
    metadata:
      labels:
        app: notify
        istio: monitor
    spec:
      containers:
        - image: esdg9t1/notify:latest
          imagePullPolicy: Always
          name: notify
          env:
            - name: SERVICE
              value: notify
          ports:
            - name: http
              containerPort: 8080
