---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
        istio: monitor
    spec:
      containers:
        - image: esdg9t1/payments:latest
          imagePullPolicy: Always
          name: payments
          env:
            - name: SERVICE
              value: payments
          ports:
            - name: http
              containerPort: 8080
