apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-resolved.yaml
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: meili
  name: meili
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: meili
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-resolved.yaml
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/carbon-marketplace-backend-backend-bridged-network: "true"
        io.kompose.service: meili
    spec:
      containers:
        - image: getmeili/meilisearch
          name: meili-search
          ports:
            - containerPort: 7700
          resources: {}
          volumeMounts:
            - mountPath: /data.ms
              name: search-data
      restartPolicy: Always
      volumes:
        - name: search-data
          persistentVolumeClaim:
            claimName: search-data
status: {}
