apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-resolved.yaml
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: payments
  name: payments
spec:
  ports:
    - name: "15002"
      port: 15002
      targetPort: 5000
  selector:
    io.kompose.service: payments
status:
  loadBalancer: {}
