apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-resolved.yaml
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: projects
  name: projects
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: projects
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-resolved.yaml
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/carbon-marketplace-backend-backend-bridged-network: "true"
        io.kompose.service: projects
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: projects
            - name: POSTGRES_HOSTNAME
              value: postgres
            - name: POSTGRES_PASSWORD
              value: changeme
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: someuser
            - name: RABBITMQ_HOSTNAME
              value: rabbitmq
            - name: RABBITMQ_PASSWORD
              value: guest
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USERNAME
              value: guest
          image: esdg9t1/projects:latest
          name: projects
          ports:
            - containerPort: 5000
          resources: {}
          volumeMounts:
            - mountPath: /app
              name: projects
      restartPolicy: Always
      volumes:
        - name: projects
          persistentVolumeClaim:
            claimName: projects
status: {}
