apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-resolved.yaml
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: users
  name: users
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: users
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-resolved.yaml
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/carbon-marketplace-backend-backend-bridged-network: "true"
        io.kompose.service: users
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: users
            - name: POSTGRES_HOSTNAME
              value: postgres
            - name: POSTGRES_PASSWORD
              value: changeme
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: someuser
          image: esdg9t1/users:latest
          name: users
          ports:
            - containerPort: 5000
          resources: {}
          volumeMounts:
            - mountPath: /app
              name: users
      restartPolicy: Always
      volumes:
        - name: users
          persistentVolumeClaim:
            claimName: users
status: {}
