version: '3'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=project
    ports:
      - "27017:27017"
  payments:
    build: 
      dockerfile: ./payments.Dockerfile
    image: payments
    ports:
      - "5008:5000"
    container_name: payments