version: '3.8'
services:
  db:
    image: postgres:15.2
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - flask_postgres

  flask:
    build: .
    container_name: flask
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - flask_postgres
  
volumes:
  db_data: {}

networks:
  flask_postgres:
    external: true