version: '3.8'

volumes:
  users_db_data: {}

services:
  users-db:
    image: postgres:13.3
    container_name: users-db
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - users_db_data:/var/lib/postgresql/data

  users-ms-flask:
    image: users-ms-flask:latest
    build: .
    container_name: users-ms-flask
    restart: always
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOSTNAME=${POSTGRES_HOSTNAME}
      - POSTGRES_PORT=${POSTGRES_PORT}
    depends_on:
      - users-db