version: '4.15.0'
services:
  db:
    image: postgres:15.2
    restart: always
    environment:
      - POSTGRES_USER=tokyobanana
      - POSTGRES_PASSWORD=naganohara
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  db_data: {}