version: "3"

networks:
  backend-bridged-network:
    driver: bridge

services:
  buy_project:
    container_name: buy_project
    image: esdg9t1/buy_project:latest
    ports:
      - 8082:8082
    volumes:
      - ./:/app
    networks:
      - backend-bridged-network
    depends_on:
      - db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: postgres # this should be the container name of the db service
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: 5432

  notify:
    container_name: notify
    image: esdg9t1/notify:latest
    ports:
      - 8081:8081
    volumes:
      - ./:/app
    networks:
      - backend-bridged-network
    depends_on:
      - db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: postgres # this should be the container name of the db service
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: 5432

  payments:
    container_name: payments
    image: esdg9t1/payments:latest
    ports:
      - 8083:8083
    volumes:
      - ./:/app
    networks:
      - backend-bridged-network
    depends_on:
      - db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: postgres # this should be the container name of the db service
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: 5432

  project_police:
    container_name: project_police
    image: esdg9t1/project_police:latest
    ports:
      - 8084:8084
    volumes:
      - ./:/app
    networks:
      - backend-bridged-network
    depends_on:
      - db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: postgres # this should be the container name of the db service
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: 5432

  projects:
    container_name: projects
    image: esdg9t1/projects:latest
    ports:
      - 8085:8085
    volumes:
      - ./:/app
    networks:
      - backend-bridged-network
    depends_on:
      - db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: postgres # this should be the container name of the db service
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: 5432

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - backend-bridged-network

  scheduler:
    container_name: scheduler
    image: esdg9t1/scheduler:latest
    ports:
      - 8086:8086
    volumes:
      - ./:/app
    networks:
      - backend-bridged-network
    depends_on:
      - db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: postgres # this should be the container name of the db service
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: 5432

  scheduler_supervisor:
    container_name: scheduler_supervisor
    image: esdg9t1/scheduler_supervisor:latest
    ports:
      - 8087:8087
    volumes:
      - ./:/app
    networks:
      - backend-bridged-network
    depends_on:
      - db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: postgres # this should be the container name of the db service
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: 5432

  search:
    container_name: search
    image: esdg9t1/search:latest
    ports:
      - 8088:8088
    volumes:
      - ./:/app
    networks:
      - backend-bridged-network
    depends_on:
      - db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: postgres # this should be the container name of the db service
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: 5432

  users:
    container_name: users
    image: esdg9t1/users:latest
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    networks:
      - backend-bridged-network
    depends_on:
      - db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: postgres # this should be the container name of the db service
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: 5432

  postgres:
    container_name: postgres
    image: postgres:13.3
    ports:
      - 5432:5432
    networks:
      - backend-bridged-network
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: 5432

  mongodb:
    container_name: mongodb
    image: mongo:4.4.6
    networks:
      - backend-bridged-network
    volumes:
      - /mongo/data:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
