version: "3"

volumes:
  postgres_data: {}

networks:
  go-rest-api-network:
    driver: bridge

services:
  gin-app:
    container_name: go-rest-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    networks:
      - go-rest-api-network
    depends_on:
      - db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: postgres # this should be the container name of the db service
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: 5432

  db:
    image: postgres:latest
    restart: always
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgres
    networks:
      - go-rest-api-network
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
