name: Build and Publish Microservices Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        microservices: # following MS need to be named exactly like folder name
          - payments
          - ProjectPolice
          - projects
          - scheduler
          - search
          - users

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Determine changes
        id: changes
        run: echo "::set-output name=changed_dirs::$(git diff --name-only HEAD~1 HEAD | cut -d '/' -f1 | uniq)"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        if: contains(steps.changes.outputs.changed_dirs, matrix.microservices)
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.microservices }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.microservices }}:latest
