name: Build and Publish Users Service Docker Image

on:
  push:
    branches:
      - main
    paths:
      - "src/temporal_server/**"

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push project police amqp app
        uses: docker/build-push-action@v4
        with:
          context: src/temporal_server
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/temporal_server:latest # tag names MUST be lowercase
