name: Build and Publish Buy Project Service Docker Image

on:
  push:
    branches:
      - main
    paths:
      - "buy_project/**"

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push buy project app
        uses: docker/build-push-action@v4
        with:
          context: buy_project
          file: buy_project/app.Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/buy_project-app:latest # tag names MUST be lowercase

      - name: Build and push temporal worker for start payment workflow
        uses: docker/build-push-action@v4
        with:
          context: buy_project
          file: buy_project/temporal_start_payment.Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/buy_project-payment_start-tmplwrkr:latest # tag names MUST be lowercase

      - name: Build and push temporal worker for payment success workflow
        uses: docker/build-push-action@v4
        with:
          context: buy_project
          file: buy_project/temporal_payment_success.Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/buy_project-payment_failed-tmplwrkr:latest # tag names MUST be lowercase

      - name: Build and push temporal worker for payment failed workflow
        uses: docker/build-push-action@v4
        with:
          context: buy_project
          file: buy_project/temporal_payment_failed.Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/buy_project-payment_success-tmplwrkr:latest # tag names MUST be lowercase
