name: Build and Publish Project Police Service Docker Image

on:
  push:
    branches:
      - main
    paths:
      - "src/project_police/**"

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push project police app
        uses: docker/build-push-action@v4
        with:
          context: src/project_police
          file: src/project_police/app.Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/project_police-app:latest # tag names MUST be lowercase

      - name: Build and push project police temporal worker
        uses: docker/build-push-action@v4
        with:
          context: src/project_police
          file: src/project_police/temporal_worker.Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/project_police-tmplwrkr:latest # tag names MUST be lowercase
